DROP TABLE IF EXISTS p_characters;

START TRANSACTION;

CREATE TABLE p_characters (
    character_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(16) NOT NULL
);

INSERT INTO
    p_characters (character_id, name)
VALUES
    (1, 'Alice'),
    (2, 'Bob');

INSERT INTO
    p_characters (name)
VALUES
    ('Carol'),
    ('Dave'),
    ('Ellen');

ROLLBACK;