DROP TABLE IF EXISTS p_characters;

START TRANSACTION;

CREATE TABLE p_characters (
    character_id integer GENERATED BY DEFAULT AS IDENTITY, --ALWAYS AS IDENTITY PRIMARY KEY,
    name varchar(16) NOT NULL
);

INSERT INTO
    p_characters (character_id, name)
VALUES
    (995, 'Alice'),
    (996, 'Bob');

SELECT
    *
FROM
    p_characters;

TRUNCATE TABLE p_characters restart identity;

INSERT INTO
    p_characters (name)
VALUES
    ('Alice'),
    ('Bob'),
    ('Carol');

SELECT
    *
FROM
    p_characters;

ROLLBACK;